### ISSUE TITLE
PlainDate.dayOfWeek not adhering to the standard

### ISSUE THREAD

**Issue by wundersolutions-juanjo** [fullcalendar/temporal-polyfill#26] opened 2024-02-03 19:03 UTC
In the current 0.2.0 version of the polyfill, PlainDate.dayOfWeek is not returning the correct value for ISO 8601 calendars

From the current docs on PlainDate, 

> The dayOfWeek read-only property gives the weekday number that the date falls on. For the ISO 8601 calendar, the weekday number is defined as in the ISO 8601 standard: a value between 1 and 7, inclusive, with Monday being 1, and Sunday 7. For an overview, see [ISO 8601 on Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Week_dates).
> 
> Usage example:
```
date = Temporal.PlainDate.from('2006-08-24');
['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'][date.dayOfWeek - 1]; // => 'THU'
```

Testing that on a website using the https://cdn.jsdelivr.net/npm/temporal-polyfill@0.2.0/global.min.js polyfill results on dates being one day off

**Comment by digaus** [comment] 2024-02-05 07:34
Just had same observation. Day of week is not returning correct value:

![image](https://github.com/fullcalendar/temporal-polyfill/assets/15358538/89782e18-6792-40df-8abd-a91bb72eeaa4)

Would be nice if this could get a hotfix

**Comment by digaus** [comment] 2024-02-05 08:37
my current workarround:

```
 const dayIntl: Intl.DateTimeFormat = new Intl.DateTimeFormat('en-GB', { weekday: 'short' } as Intl.DateTimeFormatOptions);
        return dayIntl.format(date) as 'Sun' | 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat';
       // return [ '', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun' ][ date.dayOfWeek ] as 'Sun' | 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri'| 'Sat';
```

**Comment by arshaw** [comment] 2024-02-05 15:45
I see what's going on here. The code is internally leveraging a [zoned Date method](https://github.com/fullcalendar/temporal-polyfill/blob/552991d7aa724ad20916934a9897e00d16e46f3f/packages/temporal-polyfill/src/internal/calendarIso.ts#L94) (.getDay()) when it shouldn't be. This gives eradic results based on the current user's timezone. I'll get this fixed+released today.

**Comment by arshaw** [comment] 2024-02-06 03:37
This is fixed in [v0.2.1](https://github.com/fullcalendar/temporal-polyfill/releases/tag/v0.2.1)

Turns out I was incorrectly leveraging the timezone-sensitive `Date::getDay()` AND I had an off-by-one error when computing days-of-week, and the two bugs cancelled each other out for my particular timezone and the time of day I normally work, so I never experienced the bug (nor my CI). Fun.

**Comment by arshaw** [comment] 2024-02-06 03:37
@digaus and @wundersolutions-juanjo could you kindly check to see if things work in your timezone (even tho timezone should not matter)

**Closed by arshaw** 2024-02-06 03:37 UTC

**Comment by digaus** [comment] 2024-02-06 07:08
Yeah timezone should not matter but I can confirm, that it works now correctly with `dayOfWeek`

**Comment by wundersolutions-juanjo** [comment] 2024-02-06 08:30
Looks good, thank you very much!
